{{- if .Values.appSettingsSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-appsettings-secrets
type: Opaque
stringData:
{{- range $key, $val := .Values.appSettingsSecrets }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
